project:
  type: website
  output-dir: docs

website:
  title: "Noah Goodhart"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: CSU_proj.qmd
        text: CSU Projects

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual




